sonar.projectKey=notes-app
sonar.projectName=Notes App
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src,frontend/src
sonar.tests=backend/test,frontend/test

sonar.exclusions=backend/src/generated/**,**/node_modules/**,**/dist/**,**/coverage/**
sonar.test.inclusions=backend/test/**/*.spec.ts,frontend/test/**/*.test.ts,frontend/test/**/*.test.tsx

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info

sonar.issue.ignore.multicriteria=tailwind
sonar.issue.ignore.multicriteria.tailwind.ruleKey=css:S4662
sonar.issue.ignore.multicriteria.tailwind.resourceKey=frontend/src/index.css
